[project]
name = "agentsec-scorecard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kelvin Oteyo", email = "oteyikelvin@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
agentsec-scorecard = "agentsec_scorecard:main"

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"